version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    restart: always
    env_file:
      - ./backend/src/.env
    depends_on:
      - db
    networks:
      - app_net
    expose:
      - "8080"
    volumes:
      - dp_keys:/root/.aspnet/DataProtection-Keys

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_net

volumes:
  db_data:
  dp_keys:

networks:
  app_net:
