server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # HTTP, NOT HTTPS!!!!!!!!!!!!!!!
        # Azure uses HTTP for internal container networking
        proxy_pass http://backend/;
        proxy_http_version 1.1;
        # Those headers MUST BE SET EXPLICITLY, Nginx does not set them implicitly
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /signin- {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        # Forwarded headers are absolutely mandatory for OAuth because ASP.NET needs the original browser-facing request metadata
        # to build the correct redirect callback URI
        # Note: if you use reverse proxies then you should not make your backend public-facing
        # Let the browser use the proxy as entrypoint
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /api {
        return 301 /api/;
    }
}