server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass https://backend.bluecliff-a0b1a84a.germanywestcentral.azurecontainerapps.io/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header x-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /signin-github {
        proxy_pass https://backend.bluecliff-a0b1a84a.germanywestcentral.azurecontainerapps.io;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header x-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /signin-oidc {
        proxy_pass https://backend.bluecliff-a0b1a84a.germanywestcentral.azurecontainerapps.io;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header x-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location = /api {
        return 301 /api/;
    }
}