// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { addMoneyToPot, createPot, createRefreshToken, getAllPots, getBalanceById, getUserById, loginGoogleUser, loginUser, logoutGoogleUser, logoutUser, type Options, signUpUser, withdrawMoneyFromPot } from '../sdk.gen';
import type { AddMoneyToPotData, AddMoneyToPotResponse, CreatePotData, CreatePotError, CreateRefreshTokenData, CreateRefreshTokenError, CreateRefreshTokenResponse2, GetAllPotsData, GetAllPotsResponse2, GetBalanceByIdData, GetBalanceByIdError, GetBalanceByIdResponse2, GetUserByIdData, GetUserByIdError, GetUserByIdResponse2, LoginGoogleUserData, LoginUserData, LoginUserError, LoginUserResponse, LogoutGoogleUserData, LogoutUserData, LogoutUserError, LogoutUserResponse, SignUpUserData, SignUpUserError, SignUpUserResponse2, WithdrawMoneyFromPotData, WithdrawMoneyFromPotError, WithdrawMoneyFromPotResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getUserByIdQueryKey = (options?: Options<GetUserByIdData>) => createQueryKey('getUserById', options);

export const getUserByIdOptions = (options?: Options<GetUserByIdData>) => queryOptions<GetUserByIdResponse2, GetUserByIdError, GetUserByIdResponse2, ReturnType<typeof getUserByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getUserById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getUserByIdQueryKey(options)
});

export const getAllPotsQueryKey = (options?: Options<GetAllPotsData>) => createQueryKey('getAllPots', options);

export const getAllPotsOptions = (options?: Options<GetAllPotsData>) => queryOptions<GetAllPotsResponse2, DefaultError, GetAllPotsResponse2, ReturnType<typeof getAllPotsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAllPots({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAllPotsQueryKey(options)
});

export const createPotMutation = (options?: Partial<Options<CreatePotData>>): UseMutationOptions<unknown, CreatePotError, Options<CreatePotData>> => {
    const mutationOptions: UseMutationOptions<unknown, CreatePotError, Options<CreatePotData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createPot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const withdrawMoneyFromPotMutation = (options?: Partial<Options<WithdrawMoneyFromPotData>>): UseMutationOptions<WithdrawMoneyFromPotResponse, WithdrawMoneyFromPotError, Options<WithdrawMoneyFromPotData>> => {
    const mutationOptions: UseMutationOptions<WithdrawMoneyFromPotResponse, WithdrawMoneyFromPotError, Options<WithdrawMoneyFromPotData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await withdrawMoneyFromPot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const addMoneyToPotMutation = (options?: Partial<Options<AddMoneyToPotData>>): UseMutationOptions<AddMoneyToPotResponse, DefaultError, Options<AddMoneyToPotData>> => {
    const mutationOptions: UseMutationOptions<AddMoneyToPotResponse, DefaultError, Options<AddMoneyToPotData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await addMoneyToPot({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const signUpUserMutation = (options?: Partial<Options<SignUpUserData>>): UseMutationOptions<SignUpUserResponse2, SignUpUserError, Options<SignUpUserData>> => {
    const mutationOptions: UseMutationOptions<SignUpUserResponse2, SignUpUserError, Options<SignUpUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await signUpUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const loginUserMutation = (options?: Partial<Options<LoginUserData>>): UseMutationOptions<LoginUserResponse, LoginUserError, Options<LoginUserData>> => {
    const mutationOptions: UseMutationOptions<LoginUserResponse, LoginUserError, Options<LoginUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loginUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutUserMutation = (options?: Partial<Options<LogoutUserData>>): UseMutationOptions<LogoutUserResponse, LogoutUserError, Options<LogoutUserData>> => {
    const mutationOptions: UseMutationOptions<LogoutUserResponse, LogoutUserError, Options<LogoutUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createRefreshTokenQueryKey = (options?: Options<CreateRefreshTokenData>) => createQueryKey('createRefreshToken', options);

export const createRefreshTokenOptions = (options?: Options<CreateRefreshTokenData>) => queryOptions<CreateRefreshTokenResponse2, CreateRefreshTokenError, CreateRefreshTokenResponse2, ReturnType<typeof createRefreshTokenQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await createRefreshToken({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: createRefreshTokenQueryKey(options)
});

export const loginGoogleUserQueryKey = (options?: Options<LoginGoogleUserData>) => createQueryKey('loginGoogleUser', options);

/**
 * Redirects to Google login
 */
export const loginGoogleUserOptions = (options?: Options<LoginGoogleUserData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof loginGoogleUserQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await loginGoogleUser({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: loginGoogleUserQueryKey(options)
});

export const logoutGoogleUserMutation = (options?: Partial<Options<LogoutGoogleUserData>>): UseMutationOptions<unknown, DefaultError, Options<LogoutGoogleUserData>> => {
    const mutationOptions: UseMutationOptions<unknown, DefaultError, Options<LogoutGoogleUserData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await logoutGoogleUser({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getBalanceByIdQueryKey = (options?: Options<GetBalanceByIdData>) => createQueryKey('getBalanceById', options);

export const getBalanceByIdOptions = (options?: Options<GetBalanceByIdData>) => queryOptions<GetBalanceByIdResponse2, GetBalanceByIdError, GetBalanceByIdResponse2, ReturnType<typeof getBalanceByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBalanceById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBalanceByIdQueryKey(options)
});
