// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiAuthLogout, getApiAuthRefresh, getApiPots, getApiUsersByUserId, type Options, postApiAuthLogin, postApiAuthSignup, postApiPots } from '../sdk.gen';
import type { GetApiAuthLogoutData, GetApiAuthLogoutError, GetApiAuthLogoutResponse, GetApiAuthRefreshData, GetApiAuthRefreshError, GetApiAuthRefreshResponse, GetApiPotsData, GetApiPotsResponse, GetApiUsersByUserIdData, GetApiUsersByUserIdError, GetApiUsersByUserIdResponse, PostApiAuthLoginData, PostApiAuthLoginError, PostApiAuthLoginResponse, PostApiAuthSignupData, PostApiAuthSignupError, PostApiAuthSignupResponse, PostApiPotsData, PostApiPotsResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiUsersByUserIdQueryKey = (options: Options<GetApiUsersByUserIdData>) => createQueryKey('getApiUsersByUserId', options);

export const getApiUsersByUserIdOptions = (options: Options<GetApiUsersByUserIdData>) => queryOptions<GetApiUsersByUserIdResponse, GetApiUsersByUserIdError, GetApiUsersByUserIdResponse, ReturnType<typeof getApiUsersByUserIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiUsersByUserId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiUsersByUserIdQueryKey(options)
});

export const getApiPotsQueryKey = (options: Options<GetApiPotsData>) => createQueryKey('getApiPots', options);

export const getApiPotsOptions = (options: Options<GetApiPotsData>) => queryOptions<GetApiPotsResponse, DefaultError, GetApiPotsResponse, ReturnType<typeof getApiPotsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPots({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPotsQueryKey(options)
});

export const postApiPotsMutation = (options?: Partial<Options<PostApiPotsData>>): UseMutationOptions<PostApiPotsResponse, DefaultError, Options<PostApiPotsData>> => {
    const mutationOptions: UseMutationOptions<PostApiPotsResponse, DefaultError, Options<PostApiPotsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPots({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiAuthSignupMutation = (options?: Partial<Options<PostApiAuthSignupData>>): UseMutationOptions<PostApiAuthSignupResponse, PostApiAuthSignupError, Options<PostApiAuthSignupData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthSignupResponse, PostApiAuthSignupError, Options<PostApiAuthSignupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthSignup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postApiAuthLoginMutation = (options?: Partial<Options<PostApiAuthLoginData>>): UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostApiAuthLoginResponse, PostApiAuthLoginError, Options<PostApiAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getApiAuthLogoutQueryKey = (options?: Options<GetApiAuthLogoutData>) => createQueryKey('getApiAuthLogout', options);

export const getApiAuthLogoutOptions = (options?: Options<GetApiAuthLogoutData>) => queryOptions<GetApiAuthLogoutResponse, GetApiAuthLogoutError, GetApiAuthLogoutResponse, ReturnType<typeof getApiAuthLogoutQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAuthLogout({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAuthLogoutQueryKey(options)
});

export const getApiAuthRefreshQueryKey = (options?: Options<GetApiAuthRefreshData>) => createQueryKey('getApiAuthRefresh', options);

export const getApiAuthRefreshOptions = (options?: Options<GetApiAuthRefreshData>) => queryOptions<GetApiAuthRefreshResponse, GetApiAuthRefreshError, GetApiAuthRefreshResponse, ReturnType<typeof getApiAuthRefreshQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiAuthRefresh({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiAuthRefreshQueryKey(options)
});
