// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getApiPots, getApiUsersByUserId, type Options, postApiPots, postApiUsers } from '../sdk.gen';
import type { GetApiPotsData, GetApiPotsResponse, GetApiUsersByUserIdData, GetApiUsersByUserIdError, GetApiUsersByUserIdResponse, PostApiPotsData, PostApiPotsResponse, PostApiUsersData, PostApiUsersError, PostApiUsersResponse } from '../types.gen';

export const postApiUsersMutation = (options?: Partial<Options<PostApiUsersData>>): UseMutationOptions<PostApiUsersResponse, PostApiUsersError, Options<PostApiUsersData>> => {
    const mutationOptions: UseMutationOptions<PostApiUsersResponse, PostApiUsersError, Options<PostApiUsersData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiUsers({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getApiUsersByUserIdQueryKey = (options: Options<GetApiUsersByUserIdData>) => createQueryKey('getApiUsersByUserId', options);

export const getApiUsersByUserIdOptions = (options: Options<GetApiUsersByUserIdData>) => queryOptions<GetApiUsersByUserIdResponse, GetApiUsersByUserIdError, GetApiUsersByUserIdResponse, ReturnType<typeof getApiUsersByUserIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiUsersByUserId({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiUsersByUserIdQueryKey(options)
});

export const getApiPotsQueryKey = (options: Options<GetApiPotsData>) => createQueryKey('getApiPots', options);

export const getApiPotsOptions = (options: Options<GetApiPotsData>) => queryOptions<GetApiPotsResponse, DefaultError, GetApiPotsResponse, ReturnType<typeof getApiPotsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getApiPots({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getApiPotsQueryKey(options)
});

export const postApiPotsMutation = (options?: Partial<Options<PostApiPotsData>>): UseMutationOptions<PostApiPotsResponse, DefaultError, Options<PostApiPotsData>> => {
    const mutationOptions: UseMutationOptions<PostApiPotsResponse, DefaultError, Options<PostApiPotsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postApiPots({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
