// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5096/' | (string & {});
};

export type CreatePotRequest = {
    target: number;
    name: string;
    userId: number;
};

export type CreatePotResponse = {
    id: number;
    total: number;
    target: number;
    name: string;
    userId: number;
};

export type CreateUserRequest = {
    email: string;
    password: string;
};

export type CreateUserResponse = {
    id: number;
    email: string;
};

export type GetAllPotsRequest = {
    userId: number;
};

export type GetAllPotsResponse = {
    id: number;
    total: number;
    target: number;
};

export type GetUserByIdResponse = {
    id: number;
    email: string;
    name: null | string;
};

export type PostApiUsersData = {
    body: CreateUserRequest;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type PostApiUsersErrors = {
    /**
     * Conflict
     */
    409: string;
};

export type PostApiUsersError = PostApiUsersErrors[keyof PostApiUsersErrors];

export type PostApiUsersResponses = {
    /**
     * Created
     */
    201: CreateUserResponse;
};

export type PostApiUsersResponse = PostApiUsersResponses[keyof PostApiUsersResponses];

export type GetApiUsersByUserIdData = {
    body?: never;
    path: {
        userId: number;
    };
    query?: never;
    url: '/api/users/{userId}';
};

export type GetApiUsersByUserIdErrors = {
    /**
     * Not Found
     */
    404: string;
};

export type GetApiUsersByUserIdError = GetApiUsersByUserIdErrors[keyof GetApiUsersByUserIdErrors];

export type GetApiUsersByUserIdResponses = {
    /**
     * OK
     */
    200: GetUserByIdResponse;
};

export type GetApiUsersByUserIdResponse = GetApiUsersByUserIdResponses[keyof GetApiUsersByUserIdResponses];

export type GetApiPotsData = {
    body: GetAllPotsRequest;
    path?: never;
    query?: never;
    url: '/api/pots';
};

export type GetApiPotsResponses = {
    /**
     * OK
     */
    200: Array<GetAllPotsResponse>;
};

export type GetApiPotsResponse = GetApiPotsResponses[keyof GetApiPotsResponses];

export type PostApiPotsData = {
    body: CreatePotRequest;
    path?: never;
    query?: never;
    url: '/api/pots';
};

export type PostApiPotsResponses = {
    /**
     * Created
     */
    201: CreatePotResponse;
};

export type PostApiPotsResponse = PostApiPotsResponses[keyof PostApiPotsResponses];
