// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:7111/' | (string & {});
};

export type AddMoneyToPotRequest = {
    moneyAdded: number;
};

export type CreatePotRequest = {
    target: number;
    name: string;
};

export type CreateRefreshTokenResponse = {
    accessToken: string;
};

export type GetAllPotsResponse = {
    id: number;
    total: number;
    target: number;
    name: string;
};

export type GetBalanceByIdResponse = {
    current: number;
    income: number;
    expense: number;
};

export type GetUserByIdResponse = {
    email: string;
    name: string;
};

export type LoginUserRequest = {
    email: string;
    password: string;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type SignUpUserRequest = {
    email: string;
    password: string;
    name: string;
};

export type SignUpUserResponse = {
    id: number;
    email: string;
    name: string;
};

export type WithdrawMoneyFromPotRequest = {
    moneyWithdrawn: number;
};

export type GetUserByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type GetUserByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * OK
     */
    200: GetUserByIdResponse;
};

export type GetUserByIdResponse2 = GetUserByIdResponses[keyof GetUserByIdResponses];

export type GetAllPotsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/pots';
};

export type GetAllPotsResponses = {
    /**
     * OK
     */
    200: Array<GetAllPotsResponse>;
};

export type GetAllPotsResponse2 = GetAllPotsResponses[keyof GetAllPotsResponses];

export type CreatePotData = {
    body: CreatePotRequest;
    path?: never;
    query?: never;
    url: '/v1/pots';
};

export type CreatePotErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type CreatePotError = CreatePotErrors[keyof CreatePotErrors];

export type CreatePotResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type WithdrawMoneyFromPotData = {
    body: WithdrawMoneyFromPotRequest;
    path: {
        potId: number;
    };
    query?: never;
    url: '/v1/pots/{potId}/withdrawal';
};

export type WithdrawMoneyFromPotErrors = {
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
};

export type WithdrawMoneyFromPotError = WithdrawMoneyFromPotErrors[keyof WithdrawMoneyFromPotErrors];

export type WithdrawMoneyFromPotResponses = {
    /**
     * No Content
     */
    204: void;
};

export type WithdrawMoneyFromPotResponse = WithdrawMoneyFromPotResponses[keyof WithdrawMoneyFromPotResponses];

export type AddMoneyToPotData = {
    body: AddMoneyToPotRequest;
    path: {
        potId: number;
    };
    query?: never;
    url: '/v1/pots/{potId}/addition';
};

export type AddMoneyToPotResponses = {
    /**
     * No Content
     */
    204: void;
};

export type AddMoneyToPotResponse = AddMoneyToPotResponses[keyof AddMoneyToPotResponses];

export type SignUpUserData = {
    body: SignUpUserRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type SignUpUserErrors = {
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type SignUpUserError = SignUpUserErrors[keyof SignUpUserErrors];

export type SignUpUserResponses = {
    /**
     * Created
     */
    201: SignUpUserResponse;
};

export type SignUpUserResponse2 = SignUpUserResponses[keyof SignUpUserResponses];

export type LoginUserData = {
    body: LoginUserRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type LoginUserErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type LoginUserError = LoginUserErrors[keyof LoginUserErrors];

export type LoginUserResponses = {
    /**
     * OK
     */
    200: string;
};

export type LoginUserResponse = LoginUserResponses[keyof LoginUserResponses];

export type LogoutUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout';
};

export type LogoutUserErrors = {
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type LogoutUserError = LogoutUserErrors[keyof LogoutUserErrors];

export type LogoutUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutUserResponse = LogoutUserResponses[keyof LogoutUserResponses];

export type CreateRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh';
};

export type CreateRefreshTokenErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type CreateRefreshTokenError = CreateRefreshTokenErrors[keyof CreateRefreshTokenErrors];

export type CreateRefreshTokenResponses = {
    /**
     * OK
     */
    200: CreateRefreshTokenResponse;
};

export type CreateRefreshTokenResponse2 = CreateRefreshTokenResponses[keyof CreateRefreshTokenResponses];

export type LoginGoogleUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/login/google';
};

export type LoginGoogleUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LogoutGoogleUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout/google';
};

export type LogoutGoogleUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetBalanceByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/balances';
};

export type GetBalanceByIdErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetBalanceByIdError = GetBalanceByIdErrors[keyof GetBalanceByIdErrors];

export type GetBalanceByIdResponses = {
    /**
     * OK
     */
    200: GetBalanceByIdResponse;
};

export type GetBalanceByIdResponse2 = GetBalanceByIdResponses[keyof GetBalanceByIdResponses];
