// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCreatePotRequest = z.object({
    target: z.number().gte(0),
    name: z.string().min(1),
    userId: z.int().gte(0).lte(2147483647)
});

export const zCreatePotResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    total: z.number().gte(0),
    target: z.number().gte(0),
    name: z.string().min(1),
    userId: z.int().gte(0).lte(2147483647)
});

export const zCreateRefreshTokenResponse = z.object({
    accessToken: z.string()
});

export const zGetAllPotsRequest = z.object({
    userId: z.int().gte(0).lte(2147483647)
});

export const zGetAllPotsResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    total: z.number().gte(0),
    target: z.number().gte(0)
});

export const zGetUserByIdResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    email: z.string(),
    name: z.union([
        z.null(),
        z.string().min(1)
    ])
});

export const zLoginUserRequest = z.object({
    email: z.string(),
    password: z.string().min(8)
});

export const zProblemDetails = z.object({
    type: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    title: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    status: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    detail: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    instance: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zSignUpUserRequest = z.object({
    email: z.string(),
    password: z.string().min(8),
    name: z.string().min(1)
});

export const zSignUpUserResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    email: z.string(),
    name: z.string().min(1)
});

export const zGetApiUsersByUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiUsersByUserIdResponse = zGetUserByIdResponse;

export const zGetApiPotsData = z.object({
    body: zGetAllPotsRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiPotsResponse = z.array(zGetAllPotsResponse);

export const zPostApiPotsData = z.object({
    body: zCreatePotRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiPotsResponse = zCreatePotResponse;

export const zPostApiAuthSignupData = z.object({
    body: zSignUpUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiAuthSignupResponse = zSignUpUserResponse;

export const zPostApiAuthLoginData = z.object({
    body: zLoginUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostApiAuthLoginResponse = z.string();

export const zGetApiAuthLogoutData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zGetApiAuthLogoutResponse = z.void();

export const zGetApiAuthRefreshData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiAuthRefreshResponse = zCreateRefreshTokenResponse;
