// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAddMoneyToPotRequest = z.object({
    moneyAdded: z.number()
});

export const zCreatePotRequest = z.object({
    target: z.number().gte(0),
    name: z.string().min(1)
});

export const zCreateRefreshTokenResponse = z.object({
    accessToken: z.string()
});

export const zGetAllPotsResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    total: z.number().gte(0),
    target: z.number().gte(0),
    name: z.string().min(1)
});

export const zGetBalanceByIdResponse = z.object({
    current: z.number(),
    income: z.number(),
    expense: z.number()
});

export const zGetUserByIdResponse = z.object({
    email: z.string(),
    name: z.string().min(1)
});

export const zLoginUserRequest = z.object({
    email: z.string(),
    password: z.string().min(8)
});

export const zProblemDetails = z.object({
    type: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    title: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    status: z.optional(z.union([
        z.null(),
        z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    ])),
    detail: z.optional(z.union([
        z.null(),
        z.string()
    ])),
    instance: z.optional(z.union([
        z.null(),
        z.string()
    ]))
});

export const zSignUpUserRequest = z.object({
    email: z.string(),
    password: z.string().min(8),
    name: z.string().min(1)
});

export const zSignUpUserResponse = z.object({
    id: z.int().gte(0).lte(2147483647),
    email: z.string(),
    name: z.string().min(1)
});

export const zWithdrawMoneyFromPotRequest = z.object({
    moneyWithdrawn: z.number().gte(0)
});

export const zGetUserByIdData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetUserByIdResponse2 = zGetUserByIdResponse;

export const zGetAllPotsData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAllPotsResponse2 = z.array(zGetAllPotsResponse);

export const zCreatePotData = z.object({
    body: zCreatePotRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zWithdrawMoneyFromPotData = z.object({
    body: zWithdrawMoneyFromPotRequest,
    path: z.object({
        potId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zWithdrawMoneyFromPotResponse = z.void();

export const zAddMoneyToPotData = z.object({
    body: zAddMoneyToPotRequest,
    path: z.object({
        potId: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    }),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zAddMoneyToPotResponse = z.void();

export const zSignUpUserData = z.object({
    body: zSignUpUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zSignUpUserResponse2 = zSignUpUserResponse;

export const zLoginUserData = z.object({
    body: zLoginUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zLoginUserResponse = z.string();

export const zLogoutUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * No Content
 */
export const zLogoutUserResponse = z.void();

export const zCreateRefreshTokenData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zCreateRefreshTokenResponse2 = zCreateRefreshTokenResponse;

export const zLoginGoogleUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zLogoutGoogleUserData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zGetBalanceByIdData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetBalanceByIdResponse2 = zGetBalanceByIdResponse;
