// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCreatePotRequest = z.object({
    target: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)
    ]),
    name: z.string(),
    userId: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zCreatePotResponse = z.object({
    id: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    total: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)
    ]),
    target: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)
    ]),
    name: z.string(),
    userId: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zCreateUserRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zCreateUserResponse = z.object({
    id: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    email: z.string()
});

export const zGetAllPotsRequest = z.object({
    userId: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ])
});

export const zGetAllPotsResponse = z.object({
    id: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    total: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)
    ]),
    target: z.union([
        z.number(),
        z.string().regex(/^-?(?:0|[1-9]\d*)(?:\.\d+)?$/)
    ])
});

export const zGetUserByIdResponse = z.object({
    id: z.union([
        z.int(),
        z.string().regex(/^-?(?:0|[1-9]\d*)$/)
    ]),
    email: z.string(),
    name: z.union([
        z.null(),
        z.string()
    ])
});

export const zPostApiUsersData = z.object({
    body: zCreateUserRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiUsersResponse = zCreateUserResponse;

export const zGetApiUsersByUserIdData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        userId: z.int()
    }),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiUsersByUserIdResponse = zGetUserByIdResponse;

export const zGetApiPotsData = z.object({
    body: zGetAllPotsRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetApiPotsResponse = z.array(zGetAllPotsResponse);

export const zPostApiPotsData = z.object({
    body: zCreatePotRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Created
 */
export const zPostApiPotsResponse = zCreatePotResponse;
