/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Pathless_root_layoutRouteImport } from './routes/_pathless_root_layout'
import { Route as PathlessRootLayoutIndexRouteImport } from './routes/_pathless-root-layout/index'
import { Route as PathlessRootLayoutPathlessDashboardLayoutRouteImport } from './routes/_pathless-root-layout/_pathless-dashboard-layout'
import { Route as PathlessRootLayoutPathlessAuthLayoutRouteImport } from './routes/_pathless-root-layout/_pathless-auth-layout'
import { Route as PathlessRootLayoutPathlessDashboardLayoutPotsRouteImport } from './routes/_pathless-root-layout/_pathless-dashboard-layout/pots'
import { Route as PathlessRootLayoutPathlessDashboardLayoutDashboardRouteImport } from './routes/_pathless-root-layout/_pathless-dashboard-layout/dashboard'
import { Route as PathlessRootLayoutPathlessAuthLayoutSignupRouteImport } from './routes/_pathless-root-layout/_pathless-auth-layout/signup'
import { Route as PathlessRootLayoutPathlessAuthLayoutLoginRouteImport } from './routes/_pathless-root-layout/_pathless-auth-layout/login'

const Pathless_root_layoutRoute = Pathless_root_layoutRouteImport.update({
  id: '/_pathless_root_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessRootLayoutIndexRoute = PathlessRootLayoutIndexRouteImport.update({
  id: '/_pathless-root-layout/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessRootLayoutPathlessDashboardLayoutRoute =
  PathlessRootLayoutPathlessDashboardLayoutRouteImport.update({
    id: '/_pathless-root-layout/_pathless-dashboard-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const PathlessRootLayoutPathlessAuthLayoutRoute =
  PathlessRootLayoutPathlessAuthLayoutRouteImport.update({
    id: '/_pathless-root-layout/_pathless-auth-layout',
    getParentRoute: () => rootRouteImport,
  } as any)
const PathlessRootLayoutPathlessDashboardLayoutPotsRoute =
  PathlessRootLayoutPathlessDashboardLayoutPotsRouteImport.update({
    id: '/pots',
    path: '/pots',
    getParentRoute: () => PathlessRootLayoutPathlessDashboardLayoutRoute,
  } as any)
const PathlessRootLayoutPathlessDashboardLayoutDashboardRoute =
  PathlessRootLayoutPathlessDashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PathlessRootLayoutPathlessDashboardLayoutRoute,
  } as any)
const PathlessRootLayoutPathlessAuthLayoutSignupRoute =
  PathlessRootLayoutPathlessAuthLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => PathlessRootLayoutPathlessAuthLayoutRoute,
  } as any)
const PathlessRootLayoutPathlessAuthLayoutLoginRoute =
  PathlessRootLayoutPathlessAuthLayoutLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => PathlessRootLayoutPathlessAuthLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PathlessRootLayoutIndexRoute
  '/login': typeof PathlessRootLayoutPathlessAuthLayoutLoginRoute
  '/signup': typeof PathlessRootLayoutPathlessAuthLayoutSignupRoute
  '/dashboard': typeof PathlessRootLayoutPathlessDashboardLayoutDashboardRoute
  '/pots': typeof PathlessRootLayoutPathlessDashboardLayoutPotsRoute
}
export interface FileRoutesByTo {
  '/': typeof PathlessRootLayoutIndexRoute
  '/login': typeof PathlessRootLayoutPathlessAuthLayoutLoginRoute
  '/signup': typeof PathlessRootLayoutPathlessAuthLayoutSignupRoute
  '/dashboard': typeof PathlessRootLayoutPathlessDashboardLayoutDashboardRoute
  '/pots': typeof PathlessRootLayoutPathlessDashboardLayoutPotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_pathless_root_layout': typeof Pathless_root_layoutRoute
  '/_pathless-root-layout/_pathless-auth-layout': typeof PathlessRootLayoutPathlessAuthLayoutRouteWithChildren
  '/_pathless-root-layout/_pathless-dashboard-layout': typeof PathlessRootLayoutPathlessDashboardLayoutRouteWithChildren
  '/_pathless-root-layout/': typeof PathlessRootLayoutIndexRoute
  '/_pathless-root-layout/_pathless-auth-layout/login': typeof PathlessRootLayoutPathlessAuthLayoutLoginRoute
  '/_pathless-root-layout/_pathless-auth-layout/signup': typeof PathlessRootLayoutPathlessAuthLayoutSignupRoute
  '/_pathless-root-layout/_pathless-dashboard-layout/dashboard': typeof PathlessRootLayoutPathlessDashboardLayoutDashboardRoute
  '/_pathless-root-layout/_pathless-dashboard-layout/pots': typeof PathlessRootLayoutPathlessDashboardLayoutPotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/dashboard' | '/pots'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/dashboard' | '/pots'
  id:
    | '__root__'
    | '/_pathless_root_layout'
    | '/_pathless-root-layout/_pathless-auth-layout'
    | '/_pathless-root-layout/_pathless-dashboard-layout'
    | '/_pathless-root-layout/'
    | '/_pathless-root-layout/_pathless-auth-layout/login'
    | '/_pathless-root-layout/_pathless-auth-layout/signup'
    | '/_pathless-root-layout/_pathless-dashboard-layout/dashboard'
    | '/_pathless-root-layout/_pathless-dashboard-layout/pots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Pathless_root_layoutRoute: typeof Pathless_root_layoutRoute
  PathlessRootLayoutPathlessAuthLayoutRoute: typeof PathlessRootLayoutPathlessAuthLayoutRouteWithChildren
  PathlessRootLayoutPathlessDashboardLayoutRoute: typeof PathlessRootLayoutPathlessDashboardLayoutRouteWithChildren
  PathlessRootLayoutIndexRoute: typeof PathlessRootLayoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_pathless_root_layout': {
      id: '/_pathless_root_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof Pathless_root_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-root-layout/': {
      id: '/_pathless-root-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PathlessRootLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-root-layout/_pathless-dashboard-layout': {
      id: '/_pathless-root-layout/_pathless-dashboard-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessRootLayoutPathlessDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-root-layout/_pathless-auth-layout': {
      id: '/_pathless-root-layout/_pathless-auth-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessRootLayoutPathlessAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-root-layout/_pathless-dashboard-layout/pots': {
      id: '/_pathless-root-layout/_pathless-dashboard-layout/pots'
      path: '/pots'
      fullPath: '/pots'
      preLoaderRoute: typeof PathlessRootLayoutPathlessDashboardLayoutPotsRouteImport
      parentRoute: typeof PathlessRootLayoutPathlessDashboardLayoutRoute
    }
    '/_pathless-root-layout/_pathless-dashboard-layout/dashboard': {
      id: '/_pathless-root-layout/_pathless-dashboard-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessRootLayoutPathlessDashboardLayoutDashboardRouteImport
      parentRoute: typeof PathlessRootLayoutPathlessDashboardLayoutRoute
    }
    '/_pathless-root-layout/_pathless-auth-layout/signup': {
      id: '/_pathless-root-layout/_pathless-auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PathlessRootLayoutPathlessAuthLayoutSignupRouteImport
      parentRoute: typeof PathlessRootLayoutPathlessAuthLayoutRoute
    }
    '/_pathless-root-layout/_pathless-auth-layout/login': {
      id: '/_pathless-root-layout/_pathless-auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessRootLayoutPathlessAuthLayoutLoginRouteImport
      parentRoute: typeof PathlessRootLayoutPathlessAuthLayoutRoute
    }
  }
}

interface PathlessRootLayoutPathlessAuthLayoutRouteChildren {
  PathlessRootLayoutPathlessAuthLayoutLoginRoute: typeof PathlessRootLayoutPathlessAuthLayoutLoginRoute
  PathlessRootLayoutPathlessAuthLayoutSignupRoute: typeof PathlessRootLayoutPathlessAuthLayoutSignupRoute
}

const PathlessRootLayoutPathlessAuthLayoutRouteChildren: PathlessRootLayoutPathlessAuthLayoutRouteChildren =
  {
    PathlessRootLayoutPathlessAuthLayoutLoginRoute:
      PathlessRootLayoutPathlessAuthLayoutLoginRoute,
    PathlessRootLayoutPathlessAuthLayoutSignupRoute:
      PathlessRootLayoutPathlessAuthLayoutSignupRoute,
  }

const PathlessRootLayoutPathlessAuthLayoutRouteWithChildren =
  PathlessRootLayoutPathlessAuthLayoutRoute._addFileChildren(
    PathlessRootLayoutPathlessAuthLayoutRouteChildren,
  )

interface PathlessRootLayoutPathlessDashboardLayoutRouteChildren {
  PathlessRootLayoutPathlessDashboardLayoutDashboardRoute: typeof PathlessRootLayoutPathlessDashboardLayoutDashboardRoute
  PathlessRootLayoutPathlessDashboardLayoutPotsRoute: typeof PathlessRootLayoutPathlessDashboardLayoutPotsRoute
}

const PathlessRootLayoutPathlessDashboardLayoutRouteChildren: PathlessRootLayoutPathlessDashboardLayoutRouteChildren =
  {
    PathlessRootLayoutPathlessDashboardLayoutDashboardRoute:
      PathlessRootLayoutPathlessDashboardLayoutDashboardRoute,
    PathlessRootLayoutPathlessDashboardLayoutPotsRoute:
      PathlessRootLayoutPathlessDashboardLayoutPotsRoute,
  }

const PathlessRootLayoutPathlessDashboardLayoutRouteWithChildren =
  PathlessRootLayoutPathlessDashboardLayoutRoute._addFileChildren(
    PathlessRootLayoutPathlessDashboardLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Pathless_root_layoutRoute: Pathless_root_layoutRoute,
  PathlessRootLayoutPathlessAuthLayoutRoute:
    PathlessRootLayoutPathlessAuthLayoutRouteWithChildren,
  PathlessRootLayoutPathlessDashboardLayoutRoute:
    PathlessRootLayoutPathlessDashboardLayoutRouteWithChildren,
  PathlessRootLayoutIndexRoute: PathlessRootLayoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
