/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PathlessDashboardLayoutRouteImport } from './routes/_pathless-dashboard-layout'
import { Route as PathlessAuthLayoutRouteImport } from './routes/_pathless-auth-layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PathlessDashboardLayoutTransactionsRouteImport } from './routes/_pathless-dashboard-layout/transactions'
import { Route as PathlessDashboardLayoutPotsRouteImport } from './routes/_pathless-dashboard-layout/pots'
import { Route as PathlessDashboardLayoutDashboardRouteImport } from './routes/_pathless-dashboard-layout/dashboard'
import { Route as PathlessDashboardLayoutBudgetsRouteImport } from './routes/_pathless-dashboard-layout/budgets'
import { Route as PathlessDashboardLayoutBillsRouteImport } from './routes/_pathless-dashboard-layout/bills'
import { Route as PathlessAuthLayoutSignupRouteImport } from './routes/_pathless-auth-layout/signup'
import { Route as PathlessAuthLayoutLoginRouteImport } from './routes/_pathless-auth-layout/login'

const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessDashboardLayoutRoute = PathlessDashboardLayoutRouteImport.update({
  id: '/_pathless-dashboard-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessAuthLayoutRoute = PathlessAuthLayoutRouteImport.update({
  id: '/_pathless-auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessDashboardLayoutTransactionsRoute =
  PathlessDashboardLayoutTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => PathlessDashboardLayoutRoute,
  } as any)
const PathlessDashboardLayoutPotsRoute =
  PathlessDashboardLayoutPotsRouteImport.update({
    id: '/pots',
    path: '/pots',
    getParentRoute: () => PathlessDashboardLayoutRoute,
  } as any)
const PathlessDashboardLayoutDashboardRoute =
  PathlessDashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => PathlessDashboardLayoutRoute,
  } as any)
const PathlessDashboardLayoutBudgetsRoute =
  PathlessDashboardLayoutBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => PathlessDashboardLayoutRoute,
  } as any)
const PathlessDashboardLayoutBillsRoute =
  PathlessDashboardLayoutBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => PathlessDashboardLayoutRoute,
  } as any)
const PathlessAuthLayoutSignupRoute =
  PathlessAuthLayoutSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => PathlessAuthLayoutRoute,
  } as any)
const PathlessAuthLayoutLoginRoute = PathlessAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PathlessAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof PathlessAuthLayoutLoginRoute
  '/signup': typeof PathlessAuthLayoutSignupRoute
  '/bills': typeof PathlessDashboardLayoutBillsRoute
  '/budgets': typeof PathlessDashboardLayoutBudgetsRoute
  '/dashboard': typeof PathlessDashboardLayoutDashboardRoute
  '/pots': typeof PathlessDashboardLayoutPotsRoute
  '/transactions': typeof PathlessDashboardLayoutTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/redirect': typeof RedirectRoute
  '/login': typeof PathlessAuthLayoutLoginRoute
  '/signup': typeof PathlessAuthLayoutSignupRoute
  '/bills': typeof PathlessDashboardLayoutBillsRoute
  '/budgets': typeof PathlessDashboardLayoutBudgetsRoute
  '/dashboard': typeof PathlessDashboardLayoutDashboardRoute
  '/pots': typeof PathlessDashboardLayoutPotsRoute
  '/transactions': typeof PathlessDashboardLayoutTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathless-auth-layout': typeof PathlessAuthLayoutRouteWithChildren
  '/_pathless-dashboard-layout': typeof PathlessDashboardLayoutRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/_pathless-auth-layout/login': typeof PathlessAuthLayoutLoginRoute
  '/_pathless-auth-layout/signup': typeof PathlessAuthLayoutSignupRoute
  '/_pathless-dashboard-layout/bills': typeof PathlessDashboardLayoutBillsRoute
  '/_pathless-dashboard-layout/budgets': typeof PathlessDashboardLayoutBudgetsRoute
  '/_pathless-dashboard-layout/dashboard': typeof PathlessDashboardLayoutDashboardRoute
  '/_pathless-dashboard-layout/pots': typeof PathlessDashboardLayoutPotsRoute
  '/_pathless-dashboard-layout/transactions': typeof PathlessDashboardLayoutTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/redirect'
    | '/login'
    | '/signup'
    | '/bills'
    | '/budgets'
    | '/dashboard'
    | '/pots'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/redirect'
    | '/login'
    | '/signup'
    | '/bills'
    | '/budgets'
    | '/dashboard'
    | '/pots'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_pathless-auth-layout'
    | '/_pathless-dashboard-layout'
    | '/redirect'
    | '/_pathless-auth-layout/login'
    | '/_pathless-auth-layout/signup'
    | '/_pathless-dashboard-layout/bills'
    | '/_pathless-dashboard-layout/budgets'
    | '/_pathless-dashboard-layout/dashboard'
    | '/_pathless-dashboard-layout/pots'
    | '/_pathless-dashboard-layout/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessAuthLayoutRoute: typeof PathlessAuthLayoutRouteWithChildren
  PathlessDashboardLayoutRoute: typeof PathlessDashboardLayoutRouteWithChildren
  RedirectRoute: typeof RedirectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-dashboard-layout': {
      id: '/_pathless-dashboard-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-auth-layout': {
      id: '/_pathless-auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PathlessAuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathless-dashboard-layout/transactions': {
      id: '/_pathless-dashboard-layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof PathlessDashboardLayoutTransactionsRouteImport
      parentRoute: typeof PathlessDashboardLayoutRoute
    }
    '/_pathless-dashboard-layout/pots': {
      id: '/_pathless-dashboard-layout/pots'
      path: '/pots'
      fullPath: '/pots'
      preLoaderRoute: typeof PathlessDashboardLayoutPotsRouteImport
      parentRoute: typeof PathlessDashboardLayoutRoute
    }
    '/_pathless-dashboard-layout/dashboard': {
      id: '/_pathless-dashboard-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PathlessDashboardLayoutDashboardRouteImport
      parentRoute: typeof PathlessDashboardLayoutRoute
    }
    '/_pathless-dashboard-layout/budgets': {
      id: '/_pathless-dashboard-layout/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof PathlessDashboardLayoutBudgetsRouteImport
      parentRoute: typeof PathlessDashboardLayoutRoute
    }
    '/_pathless-dashboard-layout/bills': {
      id: '/_pathless-dashboard-layout/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof PathlessDashboardLayoutBillsRouteImport
      parentRoute: typeof PathlessDashboardLayoutRoute
    }
    '/_pathless-auth-layout/signup': {
      id: '/_pathless-auth-layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PathlessAuthLayoutSignupRouteImport
      parentRoute: typeof PathlessAuthLayoutRoute
    }
    '/_pathless-auth-layout/login': {
      id: '/_pathless-auth-layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PathlessAuthLayoutLoginRouteImport
      parentRoute: typeof PathlessAuthLayoutRoute
    }
  }
}

interface PathlessAuthLayoutRouteChildren {
  PathlessAuthLayoutLoginRoute: typeof PathlessAuthLayoutLoginRoute
  PathlessAuthLayoutSignupRoute: typeof PathlessAuthLayoutSignupRoute
}

const PathlessAuthLayoutRouteChildren: PathlessAuthLayoutRouteChildren = {
  PathlessAuthLayoutLoginRoute: PathlessAuthLayoutLoginRoute,
  PathlessAuthLayoutSignupRoute: PathlessAuthLayoutSignupRoute,
}

const PathlessAuthLayoutRouteWithChildren =
  PathlessAuthLayoutRoute._addFileChildren(PathlessAuthLayoutRouteChildren)

interface PathlessDashboardLayoutRouteChildren {
  PathlessDashboardLayoutBillsRoute: typeof PathlessDashboardLayoutBillsRoute
  PathlessDashboardLayoutBudgetsRoute: typeof PathlessDashboardLayoutBudgetsRoute
  PathlessDashboardLayoutDashboardRoute: typeof PathlessDashboardLayoutDashboardRoute
  PathlessDashboardLayoutPotsRoute: typeof PathlessDashboardLayoutPotsRoute
  PathlessDashboardLayoutTransactionsRoute: typeof PathlessDashboardLayoutTransactionsRoute
}

const PathlessDashboardLayoutRouteChildren: PathlessDashboardLayoutRouteChildren =
  {
    PathlessDashboardLayoutBillsRoute: PathlessDashboardLayoutBillsRoute,
    PathlessDashboardLayoutBudgetsRoute: PathlessDashboardLayoutBudgetsRoute,
    PathlessDashboardLayoutDashboardRoute:
      PathlessDashboardLayoutDashboardRoute,
    PathlessDashboardLayoutPotsRoute: PathlessDashboardLayoutPotsRoute,
    PathlessDashboardLayoutTransactionsRoute:
      PathlessDashboardLayoutTransactionsRoute,
  }

const PathlessDashboardLayoutRouteWithChildren =
  PathlessDashboardLayoutRoute._addFileChildren(
    PathlessDashboardLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessAuthLayoutRoute: PathlessAuthLayoutRouteWithChildren,
  PathlessDashboardLayoutRoute: PathlessDashboardLayoutRouteWithChildren,
  RedirectRoute: RedirectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
